name: Build and Package for Linux
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  linux:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v3

      - name: Install dependencies
        run: npm ci

      - name: Set version from tag
        run: npm version "${GITHUB_REF#refs/tags/v}" --no-git-tag-version --allow-same-version

      - name: Build
        run: npm run build

      - name: Package (Linux)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package:linux:publish

      - name: Set version from tag (without pre-release)
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/tags/v}" | sed 's/-.*//')
          npm version "$VERSION" --no-git-tag-version --allow-same-version

      - name: Package (Snap)
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: npm run package:linux:snap

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Snap Artifacts
          retention-days: 60
          path: |
            dist/**/*.snap
