name: Build and Package for Linux
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Set version from tag
        run: npm version "${GITHUB_REF#refs/tags/v}" --no-git-tag-version --allow-same-version

      - name: Node Modules
        uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: [ 'node_modules', 'package.json', 'package-lock.json' ]
          retention-days: 1

  build:
    name: Build and Package for Linux
    runs-on: ubuntu-latest
    needs: setup
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4

      - name: Build
        run: npm run build

      - name: Build Result
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
          retention-days: 1

  package-standalone:
    name: Build and Package for Linux
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4

      - name: Package (Linux)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run package:linux:publish

  package-snap:
    name: Build and Package for Linux Snap
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4

      - name: Set version from tag (without pre-release)
        run: |
          VERSION=$(echo "${GITHUB_REF#refs/tags/v}" | sed 's/-.*//')
          npm version "$VERSION" --no-git-tag-version --allow-same-version
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        id: version

      - name: Package (Linux Snap)
        run: npm run package:linux:snap

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux Snap Artifacts
          retention-days: 60
          path: |
            dist/*.snap

      - name: Upload to Snap Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: dist/mq3t_${{ steps.version.outputs.version }}_amd64.snap
